/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 */
#ifndef __vpi_wrapper_c_end_timing_h__
#define __vpi_wrapper_c_end_timing_h__

#include <vpi_user.h>

/* registration function */
void c_end_timing_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_end_timing_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_end_timing_h__ */
