/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 */
#ifndef __vpi_wrapper_c_host_send_h__
#define __vpi_wrapper_c_host_send_h__

#include <vpi_user.h>

/* registration function */
void c_host_send_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_host_send_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_host_send_h__ */
